server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: heath-check
          uri: http://localhost:8080
          predicates:
            - Path=/health
          filters:
            - RewritePath=/health(?<segment>/?.*), /health

        - id: saldo-service
          uri: http://localhost:8081
          predicates:
            - Path=/dados-bancarios/saldo/**
          filters:
            - RewritePath=/dados-bancarios/saldo(?<segment>/?.*), /saldo$<segment>

        - id: cartao-service
          uri: http://localhost:8082
          predicates:
            - Path=/dados-bancarios/cartao/**
          filters:
            - RewritePath=/dados-bancarios/cartao(?<segment>/?.*), /cartao$<segment>

        - id: emprestimo-service
          uri: http://localhost:8083
          predicates:
            - Path=/dados-bancarios/emprestimo/**
          filters:
            - RewritePath=/dados-bancarios/emprestimo(?<segment>/?.*), /emprestimo$<segment>

        - id: pagamento-service
          uri: http://localhost:8084
          predicates:
            - Path=/dados-bancarios/pagamento/**
          filters:
            - RewritePath=/dados-bancarios/pagamento(?<segment>/?.*), /pagamento$<segment>

        # Rotas de /info
        - id: dados-cliente-service
          uri: http://localhost:8085
          predicates:
            - Path=/info/dados-cliente/**
          filters:
            - RewritePath=/info/dados-cliente(?<segment>/?.*), /dados-cliente$<segment>

        - id: configuracoes-service
          uri: http://localhost:8086
          predicates:
            - Path=/info/configuracoes/**
          filters:
            - RewritePath=/info/configuracoes(?<segment>/?.*), /configuracoes$<segment>
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
